<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Order Stock Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #003366;
            margin: 0;
        }
        .header p {
            margin: 5px 0;
            color: #555;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #008000;
            color: white;
        }
        .footer {
            text-align: center;
            margin-top: 20px;
            font-size: 0.9em;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Order Stock Report</h1>
        <p>Estate Inventory Management System</p>
        <p>Generated on {{ $generated_at }}</p>
    </div>

    <h2>Order Details</h2>
    <table>
        <tr><th>Commodity</th><td>{{ $commodity_name }}</td></tr>
        <tr><th>Current Stock</th><td>{{ $current_stock }}</td></tr>
        <tr><th>Quantity Ordered</th><td>{{ $quantity_ordered }}</td></tr>
        <tr><th>Supplier</th><td>{{ $supplier }}</td></tr>
        <tr><th>Expected Delivery</th><td>{{ $expected_delivery }}</td></tr>
        <tr><th>Urgency</th><td>{{ $urgency }}</td></tr>
        <tr><th>Notes</th><td>{{ $notes }}</td></tr>
    </table>

    <h2>Summary</h2>
    <ul>
        <li><strong>Order ID:</strong> {{ $order_id }}</li>
        <li><strong>Ordered By:</strong> {{ $ordered_by }}</li>
        <li><strong>Status:</strong> Pending</li>
    </ul>

    <div class="footer">
        <p>This report was automatically generated by the Estate Inventory Management System.</p>
    </div>
</body>
</html>

